language: ruby
rvm:
  - "2.1.1"
notifications:
  email:
    - cse403_ares@u.washington.edu
  on_success: change # default: change
  on_failure: change # default: always
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
# set environment variables, including creating a secret key
env:
  RAILS_ENV=test
  TEST_SECRET_KEY_BASE="$(bundle exec rake secret)"
