# Load environment variable for private keys in all environments,
# to avoid insecurity.

development:
  secret_key_base: <%= ENV["DEV_SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["TEST_SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
