# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e1f435759aa94d198c2e9dcbeafad3ab8d4f00614b4a6489552ca9ab0e9dd16b3f503b69f48b9797c8f4e3c6bda91797e2f30d73552152f021c8ee6ecf867fa

test:
  secret_key_base: c06b03c6dcf79488459c59bbe868c334baeccd954da047eae28da79a35734230dc89317267a5dd45ddfb2717efb8e162e57bb7e1cb7df860b353882eab248a5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
